### ISSUE TITLE
Не отправляет данные в метрику trackLinks

### ISSUE THREAD

**Issue by KCH0000** [TakNePoidet/nuxt-yandex-metrika#1]
За сутки было только 3 отправки скорее связанные с reachGoal, при этом вебвизор не отработал

```js
 yandexMetrika: {
    id: "xxxxxxxx",
    debug: IS_DEV,
    delay: 0,
    options: {
      webvisor: true,
    },
  },
```
До этого использовал  https://github.com/digitalcortex/yandex-metrika-module-nuxt3
Но там не нашел способ использовать reachGoal

**Comment by TakNePoidet** [comment]
На последнем проекте такая же проблема возникла. 
Обновил модуль  и заработало

**Comment by KCH0000** [comment]
Протестировал новую версию. В dev режиме как будто все работает, логи нормальные. В проде так же не отправляет данные в метрику никаких.

**Comment by TakNePoidet** [comment]
1. **Задержка инициализации стоит?** 
2. **Проверка находит счетчик?** <img width="661" alt="Снимок экрана 2024-06-19 в 08 58 54" src="https://github.com/TakNePoidet/nuxt-yandex-metrika/assets/23022574/d98ad82c-5f32-4c97-b168-0d33a7beea45">

**Comment by ffox07** [comment]
![изображение](https://github.com/user-attachments/assets/48fab5d9-e872-4a6f-a3c5-7b5aa962e7c2)

В функцию defu значения по умолчанию необходимо передавать последним аргументом

**Comment by KCH0000** [comment]
Попробовал еще раз с новой версией и в этот раз поставил delay 1000.
Не передаются данные.
Проверку счетчик не проходит. Пишет, что  ym undefined .
При этом в сети видно, что счетчик передает и трекает.

**Comment by KCH0000** [comment]
все протестировал, работает и статистика и reachGoal. Delay должен быть строго 0.

**Comment by KCH0000** [comment]
все протестировал, работает и статистика и reachGoal. Delay должен быть строго 0.
